### ISSUE TITLE
Issue with sorting of numeric col with null values

### ISSUE THREAD

**Issue by PavolSvidran** [PascalHonegger/ng-datatable#8]
Hello, I'am using mfDefaultSorter for string and numeric values. 

For field with only string values it works fine or with only numeric values it works fine.
For field with string and null values it still works fine, but for field with numeric and null values sorting doesn't make any sense.

Issue is simulated here: https://stackblitz.com/edit/angular-ivy-mxgxav?file=src/app/app.component.ts

Null value should be sorted to the end or start of the arr.

**Comment by PascalHonegger** [comment]
Hello, I can see the problem and the current behavior is indeed unexpected. I will probably have time this weekend to look further into this.
If you want it sooner you can also create an MR yourself (the code isn't much more familier to me than it is to you 😉 )

**Comment by PavolSvidran** [comment]
I can try if I find the time, but I'm busy now.

One more request, is it possible to update version 12 include (i know that actual is 13, but my projects strategy is to keep one version behind latest major angular version - much safer)

**Comment by PascalHonegger** [comment]
@PavolSvidran I published a fixed version in `13.1.0` in which null is treated like an empty value and always sorted to the top. This is in line with how some SQL databases treat sorting.

I don't plan on releasing this fix for Angular 12 and can recommend you update to Angular 13 as well. All libraries are updated at this point, I haven't experienced any issues so far, the build times are much better and Angular 14 is already on it's way 😉

**Comment by PavolSvidran** [comment]
Ok thanks, i update it after angular 14 release, we got some issues with early updates to new version in the past (a lot of headache for nothing - we can just wait a couple of months) and still, we are using other packages (probably are ready to v13).

**Comment by PascalHonegger** [comment]
Just saying that Angular 13 has been released at the beginning of October 2021, 3 months ago. I haven't had any issues with angular 13 in particular after updating multiple big applications. But it's your choice, as a workaround you can probably provide a custom sortBy function and map null to an empty string.

**Comment by bskohli1** [comment]
Hi, I did the upgrade to Angular 13.2.6 and updated this module to version 13.1.0. Bug is still there.

**Comment by PascalHonegger** [comment]
> Hi, I did the upgrade to Angular 13.2.6 and updated this module to version 13.1.0. Bug is still there.

HEy @bskohli1 Do you have steps to reproduce? I updated the example at [https://stackblitz.com/edit/angular-ivy-txh8tv](https://stackblitz.com/edit/angular-ivy-txh8tv) and it seems to work for me
